//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_controllerset : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Joystick
        {
            get
            {
                return SteamVR_Actions.controllerset_Joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean JumpButton
        {
            get
            {
                return SteamVR_Actions.controllerset_JumpButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean Runbutton
        {
            get
            {
                return SteamVR_Actions.controllerset_Runbutton;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.controllerset_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Skill
        {
            get
            {
                return SteamVR_Actions.controllerset_Skill;
            }
        }
        
        public virtual SteamVR_Action_Boolean Inventory
        {
            get
            {
                return SteamVR_Actions.controllerset_Inventory;
            }
        }
        
        public virtual SteamVR_Action_Boolean doWalking
        {
            get
            {
                return SteamVR_Actions.controllerset_doWalking;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.controllerset_Haptics;
            }
        }
    }
}
